version: "3.8"

services:
    proffydb:
        image: postgres:latest
        volumes:
            - server-db:/home/server/serverdb/data
        networks:
            - server-network
        container_name: "serverdb"
        restart: "always"
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=our-password
            - POSTGRES_DB=serverdb
            
networks: 
    server-network:
volumes: 
    server-db:
        